site_name: Goal-Dev-Spec
site_url: https://goal-dev-spec.github.io/goal-dev-spec/
repo_url: https://github.com/goal-dev-spec/goal-dev-spec
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Commands: commands.md
  - AI Integration: ai-integration.md
  - Governance: governance.md
  - Analytics: analytics.md
  - Automation: automation.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true