[project]
name = "goal-dev-spec"
version = "0.1.0"
description = "A goal-driven development specification system using YAML"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.9.0",
    "rich>=13.0.0",
    "pyyaml>=6.0",
    "jsonschema>=4.17.3",
    "platformdirs>=3.5.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    "psutil>=5.9.0",
    "httpx>=0.27.0",
    "requests>=2.31.0",
    "packaging>=21.0",
    "readchar>=4.0.0",
    "types-pyyaml>=6.0.12.20250915",
    "types-jsonschema>=4.25.1.20250822",
]

[project.scripts]
goal = "goal_cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "ruff>=0.1.6",
    "mypy>=1.0",
    "black>=23.0",
    "pre-commit>=3.0",
    "types-psutil>=5.9.0",
    "types-toml>=0.10.0",
]
docs = [
    "mkdocs>=1.4.0",
    "mkdocs-material>=9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/goal_cli"]
