# GitHub Pages configuration
title: Goal-Dev-Spec
description: A goal-driven development specification system
theme: minima  # Using a standard theme as fallback
markdown: kramdown

# Exclude from processing
exclude:
  - vendor/

# Base URL for GitHub Pages
baseurl: "/goal-dev-spec/docs"