name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true

    - name: Set up Python
      run: |
        uv python install

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Setup Node.js for documentation theme
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install mkdocs and material theme
      run: |
        uv pip install mkdocs-material

    - name: Build documentation
      run: |
        mkdocs build

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site