name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Set up Python
      run: |
        uv python install

    - name: Create virtual environment
      run: |
        uv venv

    - name: Install project with docs dependencies
      run: |
        source .venv/bin/activate && uv pip install ".[docs]"

    - name: Build documentation
      run: |
        source .venv/bin/activate && mkdocs build

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site