name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: |
        uv python install

    - name: Build package
      run: |
        uv build

    - name: Attest
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: 'dist/*'

    - name: Publish to PyPI
      run: |
        uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}